### ISSUE TITLE
[Feature Request] Configurable Hot-key

### ISSUE THREAD

**Issue by SilmorSenedlen** [rewkha/firefox-to-deepl#1]
Good day,
It would be very nice to add ability to use configurable Hot-key to trigger text translation.
Is it possible in current architecture of you plugin?

**Comment by rewkha** [comment]
Yes it is possible, but this will increase the number of permissions required by the extension. This request is the good candidate for the next improvement

**Comment by SilmorSenedlen** [comment]
Thx for replay.
I'll look forward for it!

**Comment by citydelver** [comment]
Speaking of permissions, this would be a great improvement, but I love the fact that your extension currently does _not_ require any permissions. Could you work with _optional_ permissions?

**Comment by rewkha** [comment]
> Speaking of permissions, this would be a great improvement, but I love the fact that your extension currently does _not_ require any permissions. Could you work with _optional_ permissions?

This is the reason why I'm not implemented this feature - it not possible to implement without adding background script which will be runned on every page (and for this extension will need to have permission to access all data on all pages, which is red flag for many people). I didn't think about optional permissions, I'll check it
