### ISSUE TITLE
"/" (slash) not encoded properly

### ISSUE THREAD

**Issue by mxmlnbln** [rewkha/firefox-to-deepl#12]
When selecting text containing a "/" (slash), the text got cut at the position of the slash in the deepl url. Most likely a problem with encodeURIComponent.

Sample text:
`This is a text/snippet, which will get cut off.`

Firefox: 88.0.1
OS: macOS 11.3.1
ToDeepL: 0.5.0

**Comment by zznidar** [comment]
It seems that DeepL expects slashes to be escaped with a backslash after they have been URL-encoded. 
`text/snippet` should therefore become `text\%2Fsnippet`
