### ISSUE TITLE
[Feature Request] Reactivate previous (=source) tab after closing the DeepL translation

### ISSUE THREAD

**Issue by n3rdc0r3** [rewkha/firefox-to-deepl#2]
1st of all: Great add-on that has saved me a lot of time and clicks so far, so thank you very much!

The add-on has one major shortcoming/flaw though in its present state: After closing the tab with the DeepL translation by pressing Ctrl+W, it doesn't reactivate the previously active tab containing the text source that was translated. This definitely would have to be the standard behavior for logical reasons alone and also is the default in Firefox when closing tabs.

Instead, the add-on currently activates the tab to the right of the closed DeepL tab for me. This behavior might seem insignificant at first, but it is actually quite time-consuming/labourious - if you have to translate a lot of stuff, reactivating the desired tab after each translation by hand definitely feels cumbersome/painful and one could even say it destroys the effectiveness of the workflow in the end.

I would be very pleased if you could consider this important suggestion to improve your add-on. It would be 99% perfect then in my eyes/for my personal everyday requirements! ;)

PS: I'm using "browser.tabs.insertRelatedAfterCurrent", true (just in case this should be important information for you in any way).

**Comment by rewkha** [comment]
Now it creates new tab near active and connect created tab to opener. So after closing tab by Ctrl+W the opener should be reactivated. New version already approved and you just need to update the extension in your browser ;)

**Comment by n3rdc0r3** [comment]
Marvelous job, thank you so much for your quick reacion! Works absolutely perfectly now and is so much faster. ;)
