### ISSUE TITLE
# can't translate

### ISSUE THREAD

**Issue by tuchida** [rewkha/firefox-to-deepl#4]
If I select this text and translate `aaa #100`, open this URL `https://www.deepl.com/translator#en/en/aaa%20#100`.
`#100` becomes the second fragment identifier and disappears.

https://github.com/rewkha/firefox-to-deepl/blob/845a063647c3edfe40e151dc6e153bbe72ae20c0/src/background.js#L21
It would be better to use `encodeURIComponent` instead of `encodeURI`.

**Comment by rewkha** [comment]
@tuchida thank you for your issue. I've fixed it and submit new version to extensions.firefox

**Comment by tuchida** [comment]
When I tried it, I could not translate it.
https://github.com/rewkha/firefox-to-deepl/blob/89c6dcc676722b4beb98a5652074aa91f8b99d8e/src/background.js#L21
It's `encodeURIComponent`, not `encodeURIencodeURIComponent`.
