### ISSUE TITLE
Wrong target language based on my IP country, unable to change language in addon settings

### ISSUE THREAD

**Issue by slrslr** [rewkha/firefox-to-deepl#7]
Hello,

it appears that by default the target language match my IP address country which is a VPN in different country than mine.
In the addon settings, i can set Default language. I am not sure if it means target language, if yes, it does not list many DeepL supported languages, so i can not choose mine and i would waste the translation cycle and time manually switching to a different language each time i end up on a deepl site.

**Comment by rewkha** [comment]
Hi, I'll update the list of languages, np

**Comment by rewkha** [comment]
Done!

**Comment by slrslr** [comment]
@rewkha Hi, i see new languages in addon preferences, but unable to see the Czech language (even it is available on deepl site..)

**Comment by rewkha** [comment]
@slrslr try now

**Comment by slrslr** [comment]
@rewkha i see cz language was added. At first i have seen weird behavior where the deepl site was redirecting from
https://www.deepl.com/translator#en/cs/text here
to the language that match my IP address country. But after switching destination translation on deepl site and reload page, it now redirects properly. Some kind of cache maybe. So it works now for me... Thank you for adding many languages. I think best DeepL extension, also because of no permissions needed, thanks.

**Comment by slrslr** [comment]
I was speaking too soon, still redirects away from the cz language to the language of my IP address country. But when i set different language in addon settings, it works correctly.. only cz is issue

**Comment by rewkha** [comment]
I think the problem was in the wrong code for Czech language - I used cz, but in deepl they used cs. Fixed in 0.4.3

**Comment by slrslr** [comment]
It seems to be working, thanks for this update!
